POST http://localhost:3333/stock
Content-Type: application/json

{
    "Name": "Produto novo",
    "Model": "Modelo Teste",
    "Date": "2025-01-01",
    "Category": "Example Category"
}

###

GET http://localhost:3333/stock/9bbfce52-098e-4c98-8e27-e1478b4a14b4


###

PUT http://localhost:3333/stock/9bbfce52-098e-4c98-8e27-e1478b4a14b4
Content-Type: application/json

{
    "Name": "Deu Certo",
    "Model": "Modelo Teste",
    "Date": "2025-01-01",
    "Category": "Example Category"
}

###

DELETE http://localhost:3333/stock/cad55d15-b4c8-4cef-aa2e-ae1743c89477